networks:
  proxiable:
    external: true
    name: proxiable
  ghost-db:
    external: true

volumes:
  ghost-db: {}
  ghost-data: {}

services:       
  ghost-mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: 'ghost-mysql'  
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes: 
      - ghost-db:/var/lib/mysql
    networks:
      - ghost-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  ghost:
    image: ghost:latest
    container_name: 'ghost'
    restart: unless-stopped
    depends_on:
      - ghost-mysql
    networks:
      - proxiable
      - ghost-db
    environment:
      database__client: mysql
      database__connection__host: ghost-mysql
      database__connection__user: root
      database__connection__password: mysql
      database__connection__database: ghost
      url: https://maxbossing.de
    volumes:
      - ghost-data:/var/lib/ghost/content
