networks:
  proxiable:
    external: true
    name: proxiable
  hoarder:
    external: true
    name: hoarder

volumes:
  hoarder_meilisearch:
  hoarder_data:

services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    container_name: hoarder-web
    restart: unless-stopped
    volumes:
      - hoarder_data:/data
    env_file:
      - hoarder.env
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      DATA_DIR: /data
    networks: 
      - hoarder
      - proxiable
      
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder

  hoarder-meilisearch:
    image: getmeili/meilisearch:latest
    container_name: hoarder-meilisearch
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - hoarder_meilisearch:/meili_data
    networks:
      - hoarder
