networks:
  proxiable:
    external: true
    name: proxiable
  kanban-db:
    external: true

volumes:
  kanboard_db: {}
  kanboard_data: {}
  kanboard_plugins: {}
  kanboard_ssl: {}

services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: unless-stopped
    container_name: 'kanboard'
    depends_on: 
      - kanboard-mariadb
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:kanboard@kanboard-mariadb/kanboard
      PLUGIN_INSTALLER: true
    networks:
      - kanban-db
      - proxiable

  kanboard-mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: 'kanboard-mariadb'
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: kanboard
    volumes:  
      - kanboard_db:/var/lib/mysql
    networks:
      - kanban-db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3