networks:
  proxiable:
    external: true
    name: proxiable

volumes:
  npm_data: {}
  npm_certs: {}

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports: 
      - "80:80"
      - "81:81" #for setup configuration, the interface is later routed through npm too
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_certs:/etc/letsencrypt
    networks:
      - proxiable
