networks:
  proxiable:
    external: true
    name: proxiable
  paste:
    name: paste

volumes:
  bytebin_content: {}

services:
  paste-web: 
    image: 'ghcr.io/lucko/paste'
    container_name: 'paste-frontend'
    restart: 'unless-stopped'
    networks:
      - paste

  paste-bytebin:
    image: 'ghcr.io/lucko/bytebin'
    container_name: 'paste-backend'
    restart: 'unless-stopped'
    volumes:
      - bytebin_content:/opt/bytebin/content
    environment:
      BYTEBIN_MISC_KEYLENGTH: 5
      MAX_CONTENT_LIFETIME: 43830
      POST_RATE_LIMIT: 10
      UPDATE_RATE_LIMI: 10
      READ_RATE_LIMIT: 25
      RATE_LIMIT_PERIOD: 60
    networks:
      - paste

  paste-nginx:
    image: 'nginx:alpine'
    container_name: 'paste-nginx'
    command: ['nginx', '-g', 'daemon off;']
    depends_on: 
      - paste
      - bytebin
    networks:
      - proxiable
      - paste
    volumes:
      - /docker/data/paste/reverseproxy-nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
