## This has to be moved to a different server and connected via ssh/vpn for "real" monitoring

networks:
  proxiable:
    external: true
    name: proxiable
    
services:
    uptime-kuma:
        restart: unless-stopped
        volumes:
          - uptimekuma:/app/data
          - /var/run/docker.sock:/var/run/docker.sock
        container_name: uptimekuma
        image: louislam/uptime-kuma:1.23.13
        networks:
          proxiable:
        
volumes:
  uptimekuma:
    external: true
    name: uptimekuma